### ISSUE TITLE
error from start 

### ISSUE THREAD

**Issue by murad0522** [ofmodemsandmen/ROOterSource2203#1]
try to compile from source i get this errro 

ROOterSource2203/staging_dir/host/bin/mkhash: No such file or directory

**Comment by murad0522** [comment]
how to solve this plz ?

**Comment by murad0522** [comment]
`make V=s
bash: line 3: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 3: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
make[2]: Entering directory '/home/murad/ROOterSource2203/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/murad/ROOterSource2203/scripts/config'
make[1]: Entering directory '/home/murad/ROOterSource2203'
make[2]: Entering directory '/home/murad/ROOterSource2203'
+ mkdir -p /home/murad/ROOterSource2203/staging_dir/target-aarch64_cortex-a53_musl
+ cd /home/murad/ROOterSource2203/staging_dir/target-aarch64_cortex-a53_musl
+ mkdir -p bin lib stamp usr/include usr/lib
mkdir -p /home/murad/ROOterSource2203/build_dir/target-aarch64_cortex-a53_musl/stamp
touch /home/murad/ROOterSource2203/staging_dir/target-aarch64_cortex-a53_musl/.prepared
+ mkdir -p /home/murad/ROOterSource2203/staging_dir/host
+ cd /home/murad/ROOterSource2203/staging_dir/host
+ mkdir -p bin lib stamp usr/include usr/lib
mkdir -p /home/murad/ROOterSource2203/build_dir/host/stamp /home/murad/ROOterSource2203/staging_dir/host/include/sys
install -m0644 /home/murad/ROOterSource2203/tools/include/*.h /home/murad/ROOterSource2203/staging_dir/host/include/
install -m0644 /home/murad/ROOterSource2203/tools/include/sys/*.h /home/murad/ROOterSource2203/staging_dir/host/include/sys/
ln -snf lib /home/murad/ROOterSource2203/staging_dir/host/lib64
touch /home/murad/ROOterSource2203/staging_dir/host/.prepared
make[3]: Entering directory '/home/murad/ROOterSource2203/tools/flock'
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
make[3]: Leaving directory '/home/murad/ROOterSource2203/tools/flock'
time: tools/flock/compile#0.02#0.00#0.02
make[3]: Entering directory '/home/murad/ROOterSource2203/tools/xz'
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
bash: line 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Is a directory
mkdir -p /home/murad/ROOterSource2203/dl
SHELL= flock /home/murad/ROOterSource2203/tmp/.xz-5.2.5.tar.bz2.flock -c '  	/home/murad/ROOterSource2203/scripts/download.pl "/home/murad/ROOterSource2203/dl" "xz-5.2.5.tar.bz2" "5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df" "" "@SF/lzmautils" "http://tukaani.org/xz"    '
+ curl -f --connect-timeout 20 --retry 5 --location https://downloads.sourceforge.net/lzmautils/xz-5.2.5.tar.bz2
sh: 1: /home/murad/ROOterSource2203/staging_dir/host/bin/mkhash: Permission denied
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   313  100   313    0     0    310      0  0:00:01  0:00:01 --:--:--   310
 76 1438k   76 1103k    0     0   354k      0  0:00:04  0:00:03  0:00:01  764k
make[3]: *** [Makefile:37: /home/murad/ROOterSource2203/dl/xz-5.2.5.tar.bz2] Error 141
make[3]: Leaving directory '/home/murad/ROOterSource2203/tools/xz'
time: tools/xz/compile#0.03#0.00#3.15
curl: (23) Failure writing output to destination
    ERROR: tools/xz failed to build.
make[2]: *** [tools/Makefile:168: tools/xz/compile] Error 1
make[2]: Leaving directory '/home/murad/ROOterSource2203'
make[1]: *** [tools/Makefile:164: /home/murad/ROOterSource2203/staging_dir/host/stamp/.tools_compile_yyynyynnyyyynyyyyyynyynnyynynyyyyyyyyyyyyyyyyynynnyyyyyyy] Error 2
make[1]: Leaving directory '/home/murad/ROOterSource2203'
make: *** [/home/murad/ROOterSource2203/include/toplevel.mk:230: world] Error 2
`

**Comment by Starktomy** [comment]
you need to cleanup the ENV

**Comment by murad0522** [comment]
solved , but after last update 

thank you
